// Code generated by tools/version.go - DO NOT EDIT.

package config

import "time"

const (
	BuildTimestamp     = int64(1614199527)
	BuildDate          = "2021-02-24T21:45:27+01:00"
	Version            = "0.1.1"
	GitDirty           = true
	GitSha             = "b64c3ac4f453920c935f04a67061e9dd3941c0b4"
	GitCommitTimestamp = int64(1612756261)
	GitCommitDate      = "2021-02-08T04:51:01+01:00"
	GitBranch          = "master"
)

func BuildTime() time.Time {
	return time.Unix(BuildTimestamp, 0)
}

func GitCommitTime() time.Time {
	return time.Unix(GitCommitTimestamp, 0)
}

func GitShaShort() string {
	return GitSha[:6]
}
