// Code generated by tools/version.go - DO NOT EDIT.

package config

import "time"

const (
	BuildTimestamp     = int64(1602193485)
	BuildDate          = "2020-10-08T23:44:45+02:00"
	Version            = "0.1.0"
	GitDirty           = true
	GitSha             = "27a0f0bc5280179469832dbc37f3fe1d6f978ce7"
	GitCommitTimestamp = int64(1602193447)
	GitCommitDate      = "2020-10-08T23:44:07+02:00"
	GitBranch          = "master"
)

func BuildTime() time.Time {
	return time.Unix(BuildTimestamp, 0)
}

func GitCommitTime() time.Time {
	return time.Unix(GitCommitTimestamp, 0)
}

func GitShaShort() string {
	return GitSha[:6]
}
